=== agarraga/actividadesIFP/marcas/UF1/actividad/irlanda.dtd
<!DOCTYPE pais 
[
<!ELEMENT pais (nombre, poblacion, continente, capital, coordenadas, fotografias, costa )>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT continente (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT coordenadas (latitud, longitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT fotografias (fotografia+)>
<!ELEMENT fotografia (nombre, descripcion, url)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT costa (#PCDATA)>
]>

=== agarraga/actividadesIFP/marcas/UF1/actividad/irlanda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pais SYSTEM "irlanda.dtd">
<pais xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="irlanda.xsd">

  <nombre>Irlanda</nombre>
  <poblacion>6572728</poblacion>
  <continente>Europa</continente>
  <capital>Dublin</capital>
  <coordenadas>
    <latitud>53ยบ21</latitud>
    <longitud>06ยบ15</longitud>
  </coordenadas>
  <fotografias>
    <fotografia>
      <nombre>Ireland (MODIS).jpg</nombre>
      <descripcion>Satellite image of Ireland in October 2010</descripcion>
      <url>https://commons.wikimedia.org/wiki/File:Ireland_(MODIS).jpg</url>
    </fotografia>
  </fotografias>
  <costa>true</costa>
</pais>
